### ISSUE TITLE
No front-end after activating the plugin

### ISSUE THREAD

**Issue by ghost** [DavidCramer/pods-frontier#36]
After activating the pods-frontier plugin i get a blank page on the front-end.
The only plugins i have activated are:
Pods - Custom Content Types and Fields
Pods Frontier
WordPress Importer

![image](https://cloud.githubusercontent.com/assets/6839895/3640457/5aa4e18c-10a1-11e4-96b5-c4f43d043cac.png)

**Comment by Shelob9** [comment]
A white screen usually means a fatal error without error display enabled. In order to help you, I need to know what that error is. Can you try again with WP_DEBUG and WP_DEBUG_DISPLAY set to true in your wp-config.php:
`
define('WP_DEBUG', true );
define('WP_DEBUG_DISPLAY', true);
`
For more information on debugging in WordPress, see: http://codex.wordpress.org/Debugging_in_WordPress

**Comment by ghost** [comment]
On front-end:

`Fatal error: Call to undefined function frontier_get_regex() in /var/www/clients/client0/web7/web/wp-content/plugins/pods-frontier-1.0.x/pods-frontier.php on line 745`

LE: Seems like the cause was the Templates component which was disabled. My mistake, but there is no mentioning that the Templates component is required.

**Comment by Shelob9** [comment]
@ChainKiller The templates component should be activate automatically. My latest commit fixes the reason it wasn't.

**Comment by alexedev** [comment]
Getting the error Fatal error: Call to undefined function frontier_get_regex() in /home/peredovikby/www/bulbatour.by/wp-content/plugins/pods-frontier-1.0.x/pods-frontier.php on line 745 after transferring the site from localhost to production server. 

The Templates component is activated. 

Also there is a Fatal error: Call to undefined function pq_loadpod() in /home/peredovikby/www/bulbatour.by/wp-content/plugins/pods-frontier-1.0.x/includes/element-pod_reference.php on line 21
in admin when a page Edit Pod Template is loaded

site url is bulbatour.by

**Comment by jamesgol** [comment]
@buduguru Let me guess, there is xcache running on the production server?  I experienced this when troubleshooting another bug.  

My fix is here:
https://github.com/pods-framework/pods/pull/2437
Though it hasn't been properly tested, it at least solves the issues on my local test with and without xcache

**Comment by alexedev** [comment]
@jamesgol thanks for your suggestion. I solved it by updating PHP to higher version 5.3 (the default one on my server is 5.2 which is too old). Now the site works properly and the template editor loads, but slowly(it takes about 10! seconds). I created a ticket in the server support about updating php to version 5.4+ (it is not impossible from the isp manager, hah:-) ) and disabling xcache. Will let you know if it helps. At least I know that the problem is not with the plugin but with the server:)
